export const QUERY_KEYS = {
  ALL_SONGS: 'ALL-SONGS',
  ALL_ALBUMS: 'ALL-ALBUMS',
  ALBUM_SONGS: 'ALBUM-SONGS',
  ALL_ARTISTS: 'ALL-ARTISTS',
  ARTIST_DETAIL: 'ARTIST-DETAIL',
  ARTIST_META: 'ARTIST-META',
  ARTIST_SONGS: 'ARTIST-SONGS',
  ARTIST_ALBUMS: 'ARTIST-ALBUMS',
  RECENTLY_ADDED: 'RECENTLY-ADDED',
} as const;

export type QueryKey = (typeof QUERY_KEYS)[keyof typeof QUERY_KEYS];
